### ISSUE TITLE
config生成脚本有错误

### ISSUE THREAD

**Issue by RepentStar** [AllesUgo/Minecraft-Speed-Proxy#10]
本萌新跟着说明运行程序，在执行完config生成脚本后正常启动程序发现有如下错误
`[22-10-03_19:45:00] [WARN ] [0] 配置文件错误，不存在RemotePort或其键值没有使用整数,默认使用25565端口
[22-10-03_19:45:00] [WARN ] [0] 配置文件错误，不存在LocalPort或其键值没有使用整数,默认使用25565端口
[22-10-03_19:45:00] [WARN ] [0] 配置文件错误，不存在AllowInput或其键值没有使用布尔值,默认开启命令行控制
[22-10-03_19:45:00] [WARN ] [0] 配置文件错误，不存在DefaultEnableWhitelist或其键值没有使用布尔值,默认关闭白名单功能
`
于是猜测是生成脚本的问题，直接把输入当做字符串写进了config.json
系统：centos7

**Comment by AllesUgo** [comment]
你用什么方式生成的配置文件呢

**Comment by RepentStar** [comment]
bash <(curl -fsSL https://fastly.jsdelivr.net/gh/AllesUgo/Minecraft-Speed-Proxy@master/scripts/config.sh )
按照提示输入的

**Comment by AllesUgo** [comment]
当bash脚本工作不正常时建议使用程序内置的生成器生成，使用--help可以看到所有帮助

**Comment by bradfordzhang** [comment]
fixed by #12

**Comment by bradfordzhang** [comment]
@RepentStar 有没有兴趣给https://github.com/extrapid/extrapid 找找bug 交交pr？

**Comment by RepentStar** [comment]
@bradfordzhang 感谢邀请，今天下午就回学校了，下次回来看看
