### ISSUE TITLE
makefile问题以及一些建议

### ISSUE THREAD

**Issue by tjstjsA** [AllesUgo/Minecraft-Speed-Proxy#13]
makefile是c99的 可是代码不是c99的 导致所有for循环报错 你是怎么编译的awa还有就是CheckLogin.c建议直接加入获取玩家名字的方式

**Comment by AllesUgo** [comment]
在for中定义变量的确是c99的标准啊

**Comment by tjstjsA** [comment]
> 

![image](https://user-images.githubusercontent.com/82302759/199369816-be8c92cf-d448-4712-b638-e29c7cbcab46.png)

**Comment by AllesUgo** [comment]
已经修复，你可以重新克隆仓库试试，标准需要gnu99

**Comment by AllesUgo** [comment]
另外加入获取玩家名字的方式是什么意思

**Comment by tjstjsA** [comment]
就是在CL_CHECK里面直接引用到玩家名字 我尝试用username但是是一大串数字不是玩家名 或者有什么方法可以在CL_CHECK得到玩家真实昵称也可以告诉我awa

**Comment by AllesUgo** [comment]
CL_Check(const char*username)里的username的确就是玩家名，你是使用哪个版本的MC登录的呢，我测试一下

**Comment by tjstjsA** [comment]
1.16 Lunar客户端

**Comment by AllesUgo** [comment]
那你在登录时服务端输出中的玩家名是否正常，或者使用list命令是否能看到玩家名

**Comment by tjstjsA** [comment]
输出的正常 但是读取到的是一大串数字 我的请求主体是这样写的snprintf(buff, sizeof(buff) - 1, "GET /gvapi/?pwd=wdnmd114514ctrl1919810sbsbssb&&name=%d HTTP/1.1\r\n" "Host: 81.68.165.87\r\n" "Content-Type: application/x-www-form-urlencoded; charset=UTF-8\r\n" "\r\n",username);

**Comment by AllesUgo** [comment]
用%s

**Comment by tjstjsA** [comment]
好的 等下课我试试

**Comment by tjstjsA** [comment]
![image](https://user-images.githubusercontent.com/82302759/199385322-020dddb4-73d0-44a2-85df-799c667fa164.png)
谢谢 已经解决了

**Comment by AllesUgo** [comment]
如果是检查登录，建议使用本程序提供的方式来进行登录或者使用动态库编写相关功能，可以参考[这里](https://github.com/AllesUgo/Minecraft-Speed-Proxy#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%99%BB%E5%BD%95%E6%A3%80%E6%9F%A5%E7%BB%84%E4%BB%B6)
