### ISSUE TITLE
如何自定义motd图标

### ISSUE THREAD

**Issue by tjstjsA** [AllesUgo/Minecraft-Speed-Proxy#14]
没错 又是我 我叕来了 这次没有bug 就是来问一下如何自定义motd图标 motd.json翻了半天没找到 只有自定义文字的 网上关于这个项目的资料和教程很少 我看人家的加速IP都有图标 不知道他们是怎么弄的

**Comment by RepentStar** [comment]
https://github.com/AllesUgo/Minecraft-Speed-Proxy/issues/8
已有类似issue
