### ISSUE TITLE
提升建议

### ISSUE THREAD

**Issue by CarlSkyCoding** [AllesUgo/Minecraft-Speed-Proxy#16]
希望可以改进一下代码提高一下转发效率
您可以对比一下这两个ip的内部延迟（Hypixel 1.8.9），服务器虽然是同一台，但是转发效率截然不同
node.hypixel.arkpowered.cn
proxy.hypixel.arkpowered.cn

**Comment by AllesUgo** [comment]
如果这些程序也是开源的，希望可以提供链接。

**Comment by CarlSkyCoding** [comment]
https://github.com/ndzda/mcnser-node
