### ISSUE TITLE
可优化转发效率

### ISSUE THREAD

**Issue by layou233** [AllesUgo/Minecraft-Speed-Proxy#18]
当前的转发过程使用普通 read then write 阻塞式读写转发，但是在 Linux 下仍有优化空间。 Linux 下的 splice syscall 可以实现内核态转发，避免内核与进程间的缓冲区拷贝以及上下文切换，性能有很大提升（就是所谓的 zerocopy 技术）。

这一技术在我的 ZBProxy 里已经使用了一年以上并且经过大量加速 IP 提供商的部署，稳定可靠。但是由于我使用的 Golang 在标准库里简单封装了 splice 的实现，当时我不需要清楚原理就可以获得这一提升。在 C 中使用这一函数的具体做法是每个方向都创建一个 pipe 并启动两个 NON_BLOCKING 的 splice ，一个负责从 socket A 读到 pipe ，一个负责从 pipe 读到 socket B。由于 Linux 实现原因，中间的 pipe 暂时不能省去。转发结束后将 pipe 回收，也可以弄一个对象池复用 pipe（Go 就是这么做的）。启动 splice 时 `size_t len` 字段指定为一个非常大的数字，就能做到一次上下文切换转发极大量的数据。

另外 512 bytes 的 buffer 对我来说太小，我认为 16k bytes buffer 或者 8k bytes buffer 是一个更好的选择，因为加载地图通常会有一个非常大的数据量。

**Comment by AllesUgo** [comment]
感谢你的建议，对于你说的零拷贝的转发方式我查找了一些资料，splice syscall的使用较为复杂，我看到了使用sendfile的方式。
sendfile在现在的Linux内核支持下可以进一步通过dma来减少数据的拷贝，我认为可以用这个函数来尝试提升性能。

**Comment by layou233** [comment]
sendfile 支持从文件读取并发送到 socket 的形式，并不支持两个连接的对拷。

另外 sendfile 还对硬盘还是文件系统（忘记了）有要求。 splice 同样也支持文件到 socket 的零拷贝，是一种通用的零拷贝方式。

**Comment by AllesUgo** [comment]
我看到了，我尝试改用了splice来实现转发，但是实际上并没有带来可观的提升，或许是我没有使用非阻塞模式？

**Comment by layou233** [comment]
如果只是转发一个连接的话，提升不会很明显。在大量跑流量或者很多人同时使用的时候，CPU 和 内存占用相比是下降的。

另外不使用非阻塞的话，应该是需要很多 thread？

**Comment by AllesUgo** [comment]
client->proxy->server和server->proxy->client是两个线程，我认为就少量用户时上下文的切换和数据的拷贝带来的延迟影响很低，主要延迟应该产生在 读->写这两个过程不同时进行的问题上。
即必须完成一次read后才能send出去，这个过程即使使用了splice也不会改变，依旧要先将数据从client读入管道再从管道写入server的缓冲区。

**Comment by layou233** [comment]
读写不同时的问题目前没有好的解决方法并且不适合去解决。这会导致过多的 write 次数，从而导致过多的 TCP 发包，这中间的开销也不小，反而会提升延迟。对于普通转发来说，合理的应对办法就是使用一个更大的 buffer 让一个数据尽可能少地被分为多次发送。

对于 splice 来说，在小鸡上观察到的多人使用时关于 CPU 和 内存 方面的提升还是非常明显的，毕竟是能减少几次复制，我依然会首选这种方案。

**Comment by bradfordzhang** [comment]
fixed by v2.2.6
