### ISSUE TITLE
新的功能：关于motd的问题

### ISSUE THREAD

**Issue by CarlSkyCoding** [AllesUgo/Minecraft-Speed-Proxy#25]
希望在下一版本中，添加在服务端运行时重新读取配置文件中的motd功能

**Comment by AllesUgo** [comment]
Fixed in 1297b6cd861ca2dd2e1dc5e2c764b7eeb4d1d8a0

**Comment by AllesUgo** [comment]
Fixed in b8e77c1efa20f871b47a9153e9e9009f590ae81c
