### ISSUE TITLE
扫描ping慢断开连接卡住

### ISSUE THREAD

**Issue by Fdulo** [AllesUgo/Minecraft-Speed-Proxy#27]
![1712479053877172573343658721551](https://github.com/AllesUgo/Minecraft-Speed-Proxy/assets/166251347/3d6d04fa-f076-4db3-a7a4-a71a2237f805)
如图断开连接就无响应很长一段时间
有一点影响体验,希望可以得到解决,谢谢!

**Comment by AllesUgo** [comment]
这应该是你的客户端问题，可以用原版客户端试试还有没有这个问题，或者换个java环境
