### ISSUE TITLE
服务器图标怎么改呢

### ISSUE THREAD

**Issue by AnybaiQC** [AllesUgo/Minecraft-Speed-Proxy#28]
服务器icon在哪里改

**Comment by AllesUgo** [comment]
运行程序后会在运行目录下产生一个motd.json文件，格式参考Minecraft原始的motd格式，在里面添加图标

**Comment by AllesUgo** [comment]
参考
https://github.com/AllesUgo/Minecraft-Speed-Proxy/issues/8
