### ISSUE TITLE
无法连接hypixel

### ISSUE THREAD

**Issue by mcfishyu** [AllesUgo/Minecraft-Speed-Proxy#31]
hypixel跟新了什么以至于无法ping，服务器是香港的不会被墙，排除问题，我发现很有可能就是hypixel跟新了什么导致与无法ping

**Comment by AllesUgo** [comment]
Ping不通是指什么？
![image](https://github.com/user-attachments/assets/000c8b68-4ff9-4aab-be89-66cff0cb7495)
我这里本地可以进入服务器

**Comment by AllesUgo** [comment]
检查一下你的防火墙配置还有程序的配置

**Comment by AllesUgo** [comment]
远程服务器地址填写mc.hypixel.net，不要使用hypixel.net，用最新版试试
