### ISSUE TITLE
登录相同账号时可以实现状态转移吗

### ISSUE THREAD

**Issue by xxiaoqie** [AllesUgo/Minecraft-Speed-Proxy#32]
当登录一个已经登录的账号时，能不能实现状态转移。
比如我用某台电脑在某minecraft服务器排队，然后用另一台电脑登录同一账号的时候，可以把状态转移过去吗，也就是说不会再从头排队？

**Comment by xxiaoqie** [comment]
感觉不太可行的样子 /(ㄒoㄒ)/~~

**Comment by AllesUgo** [comment]
开启了正版验证的服务器通信是加密的，而且也存在安全问题。
