### ISSUE TITLE
可以ping通但无法连接Hypixel

### ISSUE THREAD

**Issue by Calm00** [AllesUgo/Minecraft-Speed-Proxy#33]
如图 已关闭白名单
<img width="1285" alt="截屏2024-08-08 13 53 07" src="https://github.com/user-attachments/assets/859054d5-c0d8-4b63-800d-52c1569a9d00">
<img width="1272" alt="截屏2024-08-08 13 53 16" src="https://github.com/user-attachments/assets/549234cb-6f3f-46e8-8fd6-a1c1a228b708">

**Comment by Calm00** [comment]
更换lunar端为纯净1.8.9后仍Disconnected

**Comment by AllesUgo** [comment]
确定一下你的代理设置是否正确，就是远程服务器的地址和端口，本地服务器这些设置是否正常。还有白名单的原因等等。

**Comment by AllesUgo** [comment]
还有将Hypixel服务器地址设置为mc.hypixel.net，hypixel.net域名的首选地址可能无法连接

**Comment by AllesUgo** [comment]
最新版已支持ping远程服务器，用最新版检测一下是不是代理服务器无法连接远程服务器
#35

**Comment by Calm00** [comment]
很奇怪的是我降到该项目2.3.2版本后 其他设置未改动 就可以连上了

**Comment by AllesUgo** [comment]
你用的是原版客户端吗

**Comment by Calm00** [comment]
> 你用的是原版客户端吗

我lunar端和原版都测试了 相同问题

**Comment by AllesUgo** [comment]
能提供一下代理服务器和客户端的环境吗，包括代理服务器操作系统详细版本和客户端版本

**Comment by AllesUgo** [comment]
最新版已修复该问题
