### ISSUE TITLE
程序运行就报错

### ISSUE THREAD

**Issue by IDhammaI** [AllesUgo/Minecraft-Speed-Proxy#34]
![image](https://github.com/user-attachments/assets/5e3f7ec6-67f7-46d9-8f00-b6a05dfec165)
log也是空的
![image](https://github.com/user-attachments/assets/621806d0-c49d-49c8-a0e6-27364dbf4aac)
估计存在兼容问题，此电脑是某小厂挂机宝
![image](https://github.com/user-attachments/assets/2dc4a6fd-e366-4c87-ad1e-baf19a01a403)

**Comment by AllesUgo** [comment]
下载最新版本的vc++运行库试试？

**Comment by AllesUgo** [comment]
最新版已改用静态链接，兼容性问题降低，如果还有问题请重新打开这个issue

**Comment by AllesUgo** [comment]
glibc版本太低，解决方法就是要么更新你的系统或者glibc版本，要么用编译安装的方式。建议还是用编译安装。
