### ISSUE TITLE
运行中软件中断

### ISSUE THREAD

**Issue by liuenhongUser** [AllesUgo/Minecraft-Speed-Proxy#7]
这里是错误日志
[error.log](https://github.com/AllesUgo/Minecraft-Speed-Proxy/files/9386941/error.log)

**Comment by SkyTeamWater** [comment]
能具体描述下吗

**Comment by liuenhongUser** [comment]
可能发生在玩家多次重进服务器，玩家在游戏中击杀某些生物或看见掉落可能会导致该情况（可能性低），玩家连续多次重进服务器（高），玩家被登录插件踢下线，测试服务器mc110.net

**Comment by AllesUgo** [comment]
这个问题已经修复，可以下载最新版本测试一下，如果依旧崩溃，可以反馈一下崩溃触发的条件
