### ISSUE TITLE
支持改变motd图标吗

### ISSUE THREAD

**Issue by LFMJUN** [AllesUgo/Minecraft-Speed-Proxy#8]
如题

**Comment by LFMJUN** [comment]
而且还有个功能建议，motd还不支持彩色&e等符号还是白色

**Comment by LFMJUN** [comment]
经过测试，白名单需要每次都手动开启才行，可能config里面可以设置，但是没有找到config文件在哪里

**Comment by AllesUgo** [comment]
是这样，motd会被完整的直接发送给客户端，所以MC支持什么这里就支持什么，可以抓取其他服务器的motd来看具体写法，比如图片应该默认是走base64编码放到motd.json里的。白名单的开启这块没有增加保存配置，后续考虑一下。

**Comment by LFMJUN** [comment]
![image](https://user-images.githubusercontent.com/47923014/190348218-bf661472-1866-4dec-bf21-b49699b04515.png)
我自己测试的用颜色带码是不行的，图片走base64具体在json文件中格式是怎么样的呢

**Comment by AllesUgo** [comment]
{"description":{"text":"RBS"},"players":{"max":20,"online":0},"version":{"name":"1.18.2","protocol":758},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAPbklEQVR4Xu1YB1yUx7b/6BqSeH83Gr3JL2rejV2jQVGawFKsaDSWp0ZjjBob9ijSdynLVkUsQYqUFRRUxFgAG4iogAUVFOlL70U6W9+ZmW+XEl/ycq/3kfx+HIZv55s5c+b8z5w5Z76hlH9xovo2/NVoAEB/0wCA/qYBAP1NAwD6mwYA9DcNAOhv+sMAFKjAHxD98xukpIuyu/Ku6Q8D6NaFaIh/ZHKFVCaHIpcr5AoFPGXkFbGoUBLk75r+AAA8Oa0Q0R40lMlkWDfc2JOZfgcwCIcKBenryfjv0v8BADEdTegdrNwllcpkEvLeLpFmFNb8fOPVT6L0Nb7JduzEFYfv7gtLPZ2ULW5oBAaEUi5Bq/E2qP8m/T4AbD2Vx4A24B5yGdHihbjeJTT1y50xestE1MIwyu4MtTRSe9VFvdXntJed1VoROWrzeQdRel1rG4yXEoeixbwz+h0A2GL0pDC/ymEUtzLE8xxj318Q8MGS4Elbzlk4/DLf5Yq1w+UpW6M/WBau/03kiLWXhq2N/XBNtMaiM0b7Y3IrG9BKyOVI3jtF8L8BUNlcReAEoD10ZORUL3e+MHldyHbhndjUPHFtU7sE7WEl2sayupb2+CcFS1yu6c8PGLZS9PGKyBGro/QWimbZR9U0t+L1I9Z4Z/R2AGQOeEBYkSlkUpkUXls7uryDEu12R4Ree9bU0UXYMEwUeLBi8JSgfauUs07f07cJHL4k/OPFYZ8sP6Nlc8re9wYMAUMQi/Se8F+ntwAgaiGvlUmRUiiGKF/mV2xlnvWPSe2QIDCwj2EXS6XIK2S09gQBaocO4NnNTXjf3O8fi4KHLwgaMT90+ILjz3Mr0FjMTta498z/Cr0dgBxbqLAyOzIl8FFZ4oW0Cy5HzuQWV0MjDp1EBdrHul0NDUZ/Mhw3q+ubp34T8hHj+Ke2/iPnBgw29vM+lQgsEMBoAL3GqeZWC0QeoGahiWboQX0BdA8Hn+l6szZ4ngHvH6t//rq5sw06pWBzhZy4GPknQYrWR71zlHKJVAIS+IHJQ2bwR9ueGG1zcpjp0UXbwhQ4FpAJVP9o2m7d6Rfy07OoelXqEeoGgNtoxUgmhdrmiGVjPP8+/+js2pZqqUTRJQGSSqRQZBKpHFdQRkB+RDsSFqKQd3TBJlFkvC4dMsVDf4Lnh5M9Bo3zGG3KK699A6sIcvAoevN0a69QoPyCxfYoMlxQRYa9mszRFwAxH7GkTNYBDUk5cW6X7G9mXziTfiK/IkuJXZ9G2mMYkUUmJr6nUgvFgOT72dduZCXcybx+O/PW3azOTnr3o6cShkiQQ2LTylHEQIFOrVxPUuutcnB63p4rQKwPgpCU7IpHYXd94C026ZV7wP2D/glOAYkup5KguAUlMYOTWCGJnMiUU7Fp8WmvC6vqSKQCbeBZ39LqGZLo6J/kGpDEiXjAP/uQd/aBIPohL/ohOzzl8LmHYdcfp2ShCEwUIdsa9Idkd+dJrrcIJroJY92D7roHJeNyD2Y86B8XceOxkg4DNKQeAIjN8E9LZ/3PSS41LeXQYrvrNDXOQcvIk5rBoqZ7UNNZ1EQnarwjNFKTnSlDN8qY9be5XLOtQaBWJ4Yhrm4cYuFBTWNpwJCv3FCZ6k6N+Ykac4Aae4AycKMMWZqmPp8sFqxwjXzwshivaldTe8cytwjKyJUyZKK5pnmiIeMPUOMdqAmHtCYdoj7bs2DbKWImvBQ9AChUAMD14XnhiV9aEQrbQMucYyhj78FzhHo2Al0bvrY1ly1Kikl84XcpzXZPiI4lR8f6sIYFT8PEh5rmbO97FYaU1DSOWHxYk8GHIYNsBND7X6v8whMeRSZkMMMSx6w6qmUp0LLmUuZcytBDz4x1+V4mjNrnGwsW0bUV6tkKNCz5I1f6RSVmxiY9F8U/jbz57PytZ+Hxj5Iz8pQqK/cEQLsPdnFlQe2z0AdeUIGtBs8lTtHUTE8dG74Wg6dl5aNj7pWZh8I5ENjsn6sOU6Y+ugxffcQgGDGX+6a9vbKheehCPuinzeDpWPEoE/bMDScgwcFBBEbFpeZQJp7a1gJdBk9/rpAyZK9xPQPtk0CUOVfXiq8NQyw4Qxfwgq6mt+G0o7Y3qajrCIC6rkA5CHGfS+NkVz5EAHAoxAA8dGwEWgyuphVPx5wdnpCRWVR2J6PAXnhZFxoZh3Vs2GBvarLrkkNIlfLqJjUApI0pd8Jqv/Tckid55bH3My12BVJmPB0GAOYAA/WV67FLqTDqGwcReJqe7RE9K76WFU/DnE8ZOH2yVOAefLu0Go5SKIFAnCDBqnsF1Fhk2PyVTQWiFC+UheUoeGEA5wkATaQrT8dCqMfw0bVka5mAK3trW3K0LbmUkecIO94Bv6t1b9CBp6zmzTA7GoCmJVcLPX2omSxqhjs13VXD2FvHUqjBgMLTY3gHXEbagxL5FbVm2wKpGa7ULG/o1bHl6dryNWZzqOnM4XZ816Ab9S1tJFZhzdUuhK2vRF9VyPx3ckQpuRehIpFLJDioqQGgFWBwQWPwGR0roa6VcLC1kDLlTP3h59sZ+U2tHSCFHPjKapuGqVYAtAd/GLKAP9/h7MKDkVPW+WuaeGlZcjWs+JpWwOAz/0B4SQ06q4JinRLp+aRM272ndSAGzGBqmPtoW/P0bDiaFlyIBFPXnRBX1ytxFOoDAL2R6Bn9mFfRlIuYFPKeAHQxAMqSq2fLM9hwWnOWh4YVd5AVB6yoY+m90TumthWl6o6uThhaWts4zE7QvQeMfQy+P4ETMMiT8aMfUsZe4FqATdeGC463Q3AZOto7O6V4Rpg6PVv8ozB26Dw2Zc7TZsCu4L43l09NZW7lxShxzul2IfXGQCK6GiNTOZ3SdtJNACwFALMQAG28B3QtvNLzyoRR97WMWJQ5BwEDFae7f7HS715moRKRoqS24eNFGIAVvYkNNhyDLYYSr1LOi7pHmXrq2gihDLIVUlPcdwqvIGQqtRSqE+TT/NK/zedQlmgjvTdHSM3wWMuKwpw9wqgq++IN8KYgJsOX2ECBszrUv3aMogy9IDhoWfLA3pQ5O/VVCbTHpeWNWsqBOKhhdQTciTJmDzZj8s7dg66K2sahC4TUbJ4m8n4Ywv1wHp+xK9Ryp+iLVX5oM5hxKCNvFOxnudvsDqqsb4RD+w+sKNNtYda7w4HTfEcIwz7UaFOgHjgbKnzK0HOIFSvtlRgBQB9GvQHQAbTuxbWskwgAznXEoZc7iahZTP05vME2nPes2IMtvNJelyFDK5XFNY0L9oXozvbQt2a/P8dHz4ZNTXfe7HExs6j0s8U8bQtvGDLI2mewNWcQgw35jjJh6Vh6fWQnGLX8iNmO4J1HrlxLze5AoULWLu2YsJILOU7DxJMyZlIQIUyYsFB61hx9a87Qeby5u0JwykNf2ER1NQClGkBO1eMrL452A0As8uLquqzC8hxx5WsoRZVZRZWtHSgaSNHECnDc7KKybHHFq6Ly3OLKvLKaR9kl1XUNhRW1OcWV0PiyoAzKa3FFjrjiNfCUVJbWNjU0t5EtpyTXFuhPLi6vyS2uyiupzi2pyoFSWpWLJJS9Kqwoq65HGqJM0kW7DMq9iNQrgMTlVaWfTffEAPCJV4GcUb3L1aDpgyc698vwKtGriT0YOS+cGSVSsGz3uU1FpK7ihzghQadMfDujlkPzqIcQXjj1dnZ1ovsE3KIWSwDQOVhc/+TozY1ydJBGbYQL7Tw5OmmpCQtAM0ANnaZxuohMvWzEWjKT9bUhc/kYx4WmzmvFTXX3ku86OTv6+R2tr6+NiBAx3d0uxUIYUdy6meDq6nL7NjqtyPGXfmdHZ1NTE1YOySeNLS3Nl3+JTU19eDc5iXAiiD1MiQGojAHP+vZS51grcSM5OcswtG4iC6euyNGCItXbJK2esZxheyd9sG/i3/dO1dw0ftgO07is+9Dl4uLMdHf94bt1F6KjtmzceHD//v9euaIgP48x2ywkOCg+/nplZXlwUFBRQZHvYeGG9evKSsVPnzx6+uSJuFBckJ/P4bC//27d7Zs34q5eaX7TBIbIyHimxkw0R3mAvCiwF7HiFgbdd4QK+uBVSOT44IS1psGg/CDvUt9qPSvJXHr024/2jh3pZPCZ0yz9beO+dFr8tDSHuIBQIFi1Yvn6NWtKigq3/7jZ1fHQ3p32lWVl586Idm3fEhJ06mL0OXMT46Tbt/yP+7k6Hky5mwirJODzgoMC9u/ZLQoL3bvLPvDUyZN+R5juLqEhwRt/2NDUhI4VKqXUeUB1Dv3l5eHVYSOS8s4jJvT124VcBN1zyqTorER/wUNvSVOJ11XOJJcZnx6aPJZp9Okhg/e2j13kt0ncUImWBWU0JdPNLSEh/pifb3hYqP2ObT5sr3XfrgH/cXZyEAp4WzZvfJbx+NvVK5juzol3bu3bs+tl5vMfN36/acN3MRei3Fyd+VzOju1bT/mfPH7M98RxPx7XZ9+e3W1tLb0AqB2KbIO6ltJdFw3XnxkX+cirtg2dOlWs9ACJrONl6QtePHc21+Jz57FfsqZPYM4cvn/86J9mCa4HdMo6lfg6g0grLimub6irrqkqKyvNz8+9fv1qUVEhtGdlvoiPj2tvb29sbLifklJbU9PZ2f7wwf22ttbnz5+lpaY2N7+pqalOTLxdVFhQWVlRUVEu6eoC5FVV6BMF70/0S1YAEdaOPg4l5UauCRu9PGzU9khL/g37qMcn416c++V5hCj9hPf1Q+tDl5tyv5rkMXaaz7QpbIPPnMeNcpj4XdC256XoTI/uv1AW7b17VKQyBznPd1vxdytva+8NQN1H9kd81un1osmLQobOCxw5x3/knBOfM/z+aXbk85mC0dMFXxgIJk32mjjOdayBp+HWsJ3JOQ/QSRYZvjvFkIo6bpDwhS55sXxSJ13qCondhFHdRSSQp+pik3gMTX2+idHqyPE65NRkHLuzZ1MEY2ng5DknxwIA8yNfzBZOtBEY2h2ztj+7RZQcWlCdR2ShOVWzIlFoOd8l9V4J9KpWu+e9EO7CrMQG8NLYVpVZnnYr++q1F+fjMi8+yL+TW/2yoa2OCFT2Vl01vodIFZGutzaqB/Zs7ENvbST0q4stLFCJ8wDJ9gR/dzdGj5YJ71S1EuT5GzP9h6gvALw6WA2sDUny+BYUp1zklTKiN2L6laf0Ffafp18DQER06aVZrzphQD99R/6/09sBYEIQVDWMp7sVV/8E2it/EwCibqv3rv956HcA/PlpAEB/0wCA/qYBAP1NAwD6m/7yAP4HJHWyHG9qUHMAAAAASUVORK5CYII\u003d"}

**Comment by LFMJUN** [comment]
图片问题解决了，但是颜色代码还是用不了

**Comment by AllesUgo** [comment]
{"description":{"text":"                    §9§l|MinecraftSpeedProxy|\n         §6§l§n——欢迎使用MinecraftSpeedProxy——"},"players":{"max":1,"online":99999},"version":{"name":"1.18.1","protocol":757}}

**Comment by AllesUgo** [comment]
最新版本已加入白名单默认开关功能

**Comment by LFMJUN** [comment]
![image](https://user-images.githubusercontent.com/47923014/190542457-d2eac813-c76a-4a9d-9509-69f38df721c0.png)
实测好像并没有默认开启白名单，每次启动需要手动启动，已经更新了文件

**Comment by AllesUgo** [comment]
白名单的默认开启与否需要去修改配置文件，或者通过命令行传递参数时使用附加参数，受限于不同的服务器启动方式难以自动保存完全通过命令行启动的服务器的白名单的开启状态。

**Comment by AllesUgo** [comment]
可以使用--help查看附加参数

**Comment by LFMJUN** [comment]
好的谢谢
