### ISSUE TITLE
[22-09-21_13:05:17] [ERROR] [0] 服务器内部错误，建议重新启动服务进程，您也可以将error.log发送给开发人员

### ISSUE THREAD

**Issue by black-fruit** [AllesUgo/Minecraft-Speed-Proxy#9]
[22-09-21_13:05:17] [ERROR] [0] 服务器内部错误，建议重新启动服务进程，您也可以将error.log发送给开发人员
[22-09-21_13:05:17] [ERROR] [0] 线程段错误，尝试恢复，本恢复可能造成部分资源无法完全释放

error.log:
Wed Sep 21 13:05:17 CST 2022
Linux racknerd-7b7aab 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ulimit:
8192

看到前面有问，但我依然无法解决

**Comment by AllesUgo** [comment]
触发这个的条件是什么，必然触发还是偶然触发，触发后服务器是否崩溃

**Comment by black-fruit** [comment]
不知道，只要进入服务器就会触发

**Comment by AllesUgo** [comment]
进入服务器必然触发吗，能不能成功加入服务器，还有服务器配置文件是否正常

**Comment by black-fruit** [comment]
不能加入服务器，配置文件正常，昨天改了主机名就这样了

**Comment by black-fruit** [comment]
此外在出现这个问题前也出现了进不去，版本：最新版

**Comment by AllesUgo** [comment]
可以试试不要下载发行版，直接下载源码编译。安装gcc，进入源码目录输入make即可，生成的可执行文件与源码在一起。

**Comment by bradfordzhang** [comment]
`uname -r`看下

**Comment by bradfordzhang** [comment]
> [root@racknerd-7b7aab HypixelProxy]# make
> gcc CheckLogin.c  -c -DLOG_USE_COLOR -DVERSION=\"v\" -o CheckLogin.o
> gcc cJSON.c  -c -DLOG_USE_COLOR -DVERSION=\"v\" -o cJSON.o
> gcc client.c  -c -DLOG_USE_COLOR -DVERSION=\"v\" -o client.o
> client.c: In function ‘printdata’:
> client.c:38:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
>      for (int i = 0; i < datasize; i++)
>      ^
> client.c:38:5: note: use option -std=c99 or -std=gnu99 to compile your code
> make: *** [client.o] Error 1

使用c11标准编译

**Comment by AllesUgo** [comment]
建议升级一下系统，gcc还在默认使用c99之前的协议，看得出要么gcc很老了，要么系统太老了

**Comment by black-fruit** [comment]
额，之前用旧版可以，现在都不行

**Comment by black-fruit** [comment]
要升级服务器系统很麻烦

**Comment by bradfordzhang** [comment]
> 要升级服务器系统很麻烦

那你就c99编译

**Comment by black-fruit** [comment]
> 也可以，你在Makefile的第6行ALLARGV=-O3的后面加上-std=c11再次编译试试
> 写成ALLARGV=-O3 -std=c11

依然如此

**Comment by AllesUgo** [comment]
那你用c99试试
-std=c99

**Comment by AllesUgo** [comment]
现在可以重新从仓库克隆以下，我把仓库里的makefile改成c99了

**Comment by black-fruit** [comment]
我觉得是我服务器出了点问题，它无法连接网络了

**Comment by bradfordzhang** [comment]
> > 我并不认为2022年依旧停留在3.10内核是一件正确的选择
> 
> 我也觉得，但是怎么升级都提示最新版本

什么发行版

**Comment by black-fruit** [comment]
现在网络正常了，但更新后依然无法编译

**Comment by bradfordzhang** [comment]
> 现在网络正常了，但更新后依然无法编译

你内核太久了……
编译日志呢

**Comment by black-fruit** [comment]
> > 现在网络正常了，但更新后依然无法编译
> 
> 你内核太旧了……
> 编译日志呢

跟之前一样

**Comment by black-fruit** [comment]
改c99也不行

**Comment by black-fruit** [comment]
> > > > 现在网络正常了，但更新后依然无法编译
> > > 
> > > 你内核太旧了……
> > > 编译日志呢
> > 
> > 跟之前一样
> 
> 内核/gcc太旧 

系统内核？

**Comment by bradfordzhang** [comment]
> > > > > 现在网络正常了，但更新后依然无法编译
> > > > 
> > > > 你内核太旧了……
> > > > 编译日志呢
> > > 
> > > 跟之前一样
> > 
> > 内核/gcc太旧 
> 
> 系统内核？

对

**Comment by black-fruit** [comment]
Your user’s .npmrc file (${HOME}/.npmrc)
has a `globalconfig` and/or a `prefix` setting, which are incompatible with nvm.
Run `nvm use --delete-prefix v16.15.1 --silent` to unset it.
[root@bfhui ~]# cd /www/HypixelProxy
[root@bfhui HypixelProxy]# make
gcc client.c  -c -DLOG_USE_COLOR -DVERSION=\"v\" -o client.o
client.c: In function ‘printdata’:
client.c:38:5: error: ‘for’ loop initial declarations are only allowed in C99 mo
de
     for (int i = 0; i < datasize; i++)
     ^
client.c:38:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [client.o] Error 1
[root@bfhui HypixelProxy]# yum install gcc
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                     |  21 kB     00:00
 * base: centos.mirror.shastacoe.net
 * centos-sclo-rh: mirrors.radwebhosting.com
 * epel: mirror.tornadovps.com
 * extras: mirrors.xmission.com
 * updates: mirrors.raystedman.org
base                                                     | 3.6 kB     00:00
centos-sclo-rh                                           | 3.0 kB     00:00
extras                                                   | 2.9 kB     00:00
updates                                                  | 2.9 kB     00:00
updates/7/x86_64/primary_db                                |  17 MB   00:03
Package gcc-4.8.5-44.el7.x86_64 already installed and latest version
Nothing to do
[root@bfhui HypixelProxy]#

**Comment by bradfordzhang** [comment]
gcc4.8 洗洗睡吧

**Comment by black-fruit** [comment]
> gcc4.8 洗洗睡吧

你倒是发个最新版啊yum确实没有

**Comment by bradfordzhang** [comment]
> > gcc4.8 洗洗睡吧
> 
> 你倒是发个最新版啊yum确实没有

我怎么发新版，你centos版本太低，3.10内核当然没有新版gcc。18年的ubuntu18.04都能跑 4.9内核
